# Generated by Django 5.0.3 on 2024-04-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=40)),
                ("cnp", models.IntegerField()),
                ("email", models.EmailField(max_length=60)),
                ("active", models.BooleanField(default=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=6
                    ),
                ),
                (
                    "departament",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend"),
                            ("backend", "Backend"),
                            ("cc", "Call Center"),
                            ("devops", "DevOps"),
                            ("engineering", "Software Engineering"),
                        ],
                        max_length=11,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("notice_date", models.DateField()),
                ("address", models.TextField(blank=True)),
                ("is_supervisor", models.BooleanField(default=False)),
                ("days_off", models.IntegerField(default=21)),
            ],
        ),
    ]
