# Generated by Django 5.0.3 on 2024-04-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0003_alter_department_supervisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="holidayrequest",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
