# Generated by Django 5.0.3 on 2024-04-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0005_employee_created_at_employee_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="cnp",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=60, unique=True),
        ),
    ]
