# Generated by Django 5.0.3 on 2024-04-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0006_remove_employee_is_supervisor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holidayrequest",
            name="attachment",
            field=models.FileField(upload_to="holiday_request/"),
        ),
    ]
