# Generated by Django 5.0.3 on 2024-04-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0007_alter_holidayrequest_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="days_off",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
