# Generated by Django 5.0.3 on 2024-04-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0008_alter_employee_days_off"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holidayrequest",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="holiday_request/"),
        ),
    ]
